name: Build Release APK

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build optimized release APK
        run: ./gradlew --no-daemon clean assembleRelease

      - name: Collect release artifact
        id: collect
        run: |
          APK_PATH=$(ls app/build/outputs/apk/release/*.apk | head -n 1)
          DEST_NAME="FlowBell-${{ github.event.release.tag_name }}-unsigned.apk"
          mkdir -p dist
          cp "$APK_PATH" "dist/$DEST_NAME"
          echo "asset_path=dist/$DEST_NAME" >> "$GITHUB_OUTPUT"
          echo "artifact_path=$APK_PATH" >> "$GITHUB_OUTPUT"

      - name: Upload artifact for workflow run
        uses: actions/upload-artifact@v4
        with:
          name: flowbell-release-apk
          path: ${{ steps.collect.outputs.asset_path }}

      - name: Attach APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.collect.outputs.asset_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
